Test did not pass due to include
test results with old line:
Scanning dependencies of target ram_cpp_utils_tests
[ 98%] Building CXX object ram_cpp_utils/CMakeFiles/ram_cpp_utils_tests.dir/test/ConversionTests.cpp.o
/home/jeramy/Documents/RatM/qubo/src/ram_cpp_utils/test/ConversionTests.cpp:1:45: fatal error: ram_cpp_utils/math/Conversion.hpp: No such file or directory
compilation terminated.

and new line:

[==========] Running 3 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 3 tests from ConversionTests
[ RUN      ] ConversionTests.vectorConversions
[       OK ] ConversionTests.vectorConversions (1 ms)
[ RUN      ] ConversionTests.matrixConversions
[       OK ] ConversionTests.matrixConversions (0 ms)
[ RUN      ] ConversionTests.quaternionConversions
[       OK ] ConversionTests.quaternionConversions (0 ms)
[----------] 3 tests from ConversionTests (1 ms total)

[----------] Global test environment tear-down
[==========] 3 tests from 1 test case ran. (1 ms total)
[  PASSED  ] 3 tests.

[100%] Built target _run_tests_ram_cpp_utils_gtest_ram_cpp_utils_tests
[100%] Built target _run_tests_ram_cpp_utils_gtest
[100%] Built target _run_tests_ram_cpp_utils
[100%] Built target run_tests